language: python
python:
    - "3.5"
before_install:
    - pip install pytest pytest-cov
    - pip install coveralls
    - pip install ply
    - pip install sphinx
    - pip install bintrees
    - pip install .
script:
    - python setup.py test
after_success:
    - coveralls
