language: python
python:
  - "3.5"
install:
  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  # Replace dep1 dep2 ... with your dependencies
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION numpy scipy matplotlib
  - source activate test-environment
  - pip install pytest pytest-cov
  - pip install coveralls
  - pip install ply
  - pip install sphinx
  - pip install bintrees
  - pip install asynctest
  - pip install asyncio
  - pip install aiohttp
  - pip install graphviz
  - python setup.py install

script:
    - python setup.py test

after_success:
    - coveralls
