language: python
python:
    - "3.5"
addons:
  apt:
    packages:
    - libatlas-dev
    - libatlas-base-dev
    - liblapack-dev
    - gfortran
    - python3-scipy
before_install:
    - pip install pytest pytest-cov
    - pip install coveralls
    - pip install ply
    - pip install sphinx
    - pip install bintrees
    - pip install asynctest
    - pip install asyncio
    - pip install aiohttp
    - pip install .
script:
    - python setup.py test
after_success:
    - coveralls
